python: 3.10.2
build_dependencies:
- pip==23.0.1
- setuptools==65.6.3
- wheel==0.38.4
dependencies:
- mlflow<3,>=2.3
- cloudpickle==2.2.1
- numpy==1.23.5
- pandas==2.0.0
- psutil==5.9.0
- scikit-learn==1.2.2
- scipy==1.10.1
- xgboost==1.7.5
